[package]
name = "back-check-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1.0"
csv = "1.3"
scraper = "0.23"
regex = "1.11"